### ISSUE TITLE
README Instructions fail At running step due to --address parameter

### ISSUE THREAD

**Issue by admiyo** [openshift/cincinnati#134]
Build on Fedora 30:

   Compiling policy-engine v0.1.0 (/home/ayoung/devel/cincinnati/policy-engine)
    Finished dev [unoptimized + debuginfo] target(s) in 4m 27s
     Running `target/debug/policy-engine --address 0.0.0.0`
error: Found argument '--address' which wasn't expected, or isn't valid in this context

Could this be an issue with the version of Rust used to build

Steps to repro:

git clone....
cd cincinnati/
export CINCINNATI_REGISTRY="https://quay.io"
cargo run --package graph-builder -- --address 0.0.0.0 --registry "${CINCINNATI_REGISTRY}" --repository "${CINCINNATI_REPO}" &
 cargo run --package policy-engine -- --address 0.0.0.0 

Its the last command that fails.  I got that from the README.

**Comment by lucab** [comment]
Thanks for the report! The problem is due to the documented flags being outdated compared to current codebase. The updated ones are in https://github.com/openshift/cincinnati/pull/135.

By the way if you only want to compile, you can just `cargo build`.

**Comment by admiyo** [comment]
Updated the report to reflect that it is following the README that is broken.  What are the right flags for actually running the server etc?

**Comment by lucab** [comment]
@admiyo I think you missed part of my previous reply. Right flags (and the README fix) are shown in https://github.com/openshift/cincinnati/pull/135/files.
