### ISSUE TITLE
Mechanism to Query for Channels

### ISSUE THREAD

**Issue by sferich888** [openshift/cincinnati#171]
As a user of the graph, how do I know what channels are available or presented by my Cincinnati service?

**Comment by steveej** [comment]
This depends entirely on the configuration. A channel is not a first-class element in the [Cincinnati protocol][cincinnati-docs], and is implemented only in the [openshift specifics built on top][openshift-docs] and through [the channel filter plugin][channel-filter-plugin] which expects certain metadata being available in each release to indicate the channels, and filters according to a request parameter sent by the client.

We've been configuring the graph-builder to expose the unfiltered graph. The policy-engine engine points to the graph-builder builder as its upstream, and does the filtering on each user request. If a user wanted to know all the available channels (read: have access to an unfiltered graph on which it can investigate the metadata), they would need access to the graph-builder endpoint, or to a policy-engine which doesn't have the channel-filter plugin configured.

[cincinnati-docs]: https://github.com/openshift/cincinnati/blob/288afc81696333bb0e46079b0073c0e0cd286fea/docs/design/cincinnati.md
[openshift-docs]: https://github.com/openshift/cincinnati/blob/288afc81696333bb0e46079b0073c0e0cd286fea/docs/design/openshift.md
[channel-filter-plugin]: https://github.com/openshift/cincinnati/blob/288afc81696333bb0e46079b0073c0e0cd286fea/cincinnati/src/plugins/internal/channel_filter.rs

**Comment by sferich888** [comment]
You require a parameter of channel, to query the graph. I don't know how you can get an unfiltered graph. 

So if this is required to get updates shouldn't we expose a way to list the channels, or as you say list the unfiltered graph?

**Comment by steveej** [comment]
> So if this is required to get updates shouldn't we expose a way to list the channels, or as you say list the unfiltered graph?

Yes, it will allow you to examine the available channels by looking at all release metadata.
Though, this depends entirely on the configuration of the instance we're talking about and doesn't require a new feature or code change in here. It requires a configuration in the API gateway, or whatever sits in front of the graph-builder instance we're talking about.

**Comment by sferich888** [comment]
With OpenShift as an example how do we pull the full graph?

**Comment by kbsingh** [comment]
@jhernand for visibility for anything we need at api layer

**Comment by crawford** [comment]
We will never expose the _full_ graph, since that may contain embargoed builds. Eventually, we should expose a safe graph (bonus points for providing a way to visualize the raw data) so that customers can understand the broader landscape and plan their upgrade path.

@sferich888 what use case did you have in mind for needing a list of channels?

**Comment by sferich888** [comment]
> @sferich888 what use case did you have in mind for needing a list of channels?

As a user (admin) of a cluster, how do I list or view the graph or path my cluster can take between tow versions. 

This is fairly simple to do if you know the you want to get updates from. However, we don't really provide a way to list or query for the available channels, so that graphs or path diagrams can be built. 

---

As a developer, of the console, it would be nice to not have to hard code into the UI, JS, what channels a user can select. Being able to dynamic build a list of channels is a better solution. 

- this may help with a disconnect story, if we ever let users mirror or sync graphs between Cincinnati instances.

**Comment by sferich888** [comment]
> (bonus points for providing a way to visualize the raw data) so that customers can understand the broader landscape and plan their upgrade path.

We already do/have this! https://github.com/openshift/cincinnati/blob/master/hack/graph.sh

This can be rendered with: https://visjs.org/, so it's simple a matter of exposing this to users not making (application/json requests to the Cincinnati endpoint /graph).

**Comment by steveej** [comment]
> This can be rendered with: https://visjs.org/, so it's simple a matter of exposing this to users not making (application/json requests to the Cincinnati endpoint /graph).

I'm not opposed to serving the graph as `image/svg`, so the console could render it. Is that what you're proposing?

**Comment by steveej** [comment]
> I'm not opposed to serving the graph as `image/svg`, so the console could render it. Is that what you're proposing?

That would be best discussed in a separate issue. We actually have [a ticket on our (still internal) jira instance][0].

WRT to the issue being discussed here, it's fairly simple to build a list of channels and expose it in Cincinnati. It would also be fairly simple to have the CVO compile this list after it fetches the graph from Cincinnati and expose this list in the cluster. @sferich888 Would you be opposed to the latter?

[0]: https://jira.coreos.com/browse/CIN-1

**Comment by sferich888** [comment]
I think external clients also need to be able to pull the list of channels.

**Comment by crawford** [comment]
> As a user (admin) of a cluster, how do I list or view the graph or path my cluster can take between tow versions.
>
> This is fairly simple to do if you know the you want to get updates from. However, we don't really provide a way to list or query for the available channels, so that graphs or path diagrams can be built.

Even if you have the list of channels, this is difficult to answer at a glance. You would have to fetch one graph for each channel and then reconstruct the pieces. It's certainly possible, but I think I'd rather we just showed the entire graph (which could then be parsed or rendered).

> As a developer, of the console, it would be nice to not have to hard code into the UI, JS, what channels a user can select. Being able to dynamic build a list of channels is a better solution.

I'm not convinced that it is a better solution. We were very successful with Container Linux and Core Update without this functionality and I'm a little worried that this added complexity has land mines (e.g. what if an end user with an on-prem Cincinnati changes the channel name? how do we ensure that the list of channels served to clusters is actually applicable?).

Can you elaborate a bit on why you think we need to be able to dynamically update the list of channels?

**Comment by sferich888** [comment]
I don't think we need to update I think we need the ability to query.

**Comment by steveej** [comment]
> I don't think we need to update I think we need the ability to query.

I don't understand what you mean by updating in this context, especially when opposed to being able to query.

Besides, would you mind addressing the question I asked in https://github.com/openshift/cincinnati/issues/171#issuecomment-553873421?

**Comment by sferich888** [comment]
I think things outside of the cluster (other clients) need to be able to query for the channels. Not just the cvo.

**Comment by steveej** [comment]
I think to really be able to help you I need a comprehensive use-case description. I'm trying to put the pieces together but it's still not entirely clear to me what the motivation here is.

In the original issue description you wrote _"as a user of the graph"_. How did that user retrieve the graph in question?

**Comment by wking** [comment]
You can get channels now:

```console
$ curl -sH 'Accept:application/json' 'https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.2' | jq -r '.nodes[] | select(.version == "4.2.4").metadata["io.openshift.upgrades.graph.release.channels"] | split(",")[]'
candidate-4.2
fast-4.2
stable-4.2
```

To use that from the console, we need to give ClusterVersion a place to store it, which we don't have now.

> As a user (admin) of a cluster, how do I list or view the graph or path my cluster can take between [two] versions.

I'd rather handle this with a "I'd like to be on channel" property on ClusterVersion, after which the CVO and Cincinnati would transparently suggest update targets to walk you towards your target channel without leaving your current channel.  But that sounds like a separate issue from "Query for Channels".

**Comment by sferich888** [comment]
@wking this command still requires a version (major.minor) input. We should be able to ask for 'all channels' without any input. 

@steveeJ we can discuss on slack if it would help in understanding the use case[s]. I feel the two I have given should be sufficient to understand the basis of the request.

**Comment by wking** [comment]
> We should be able to ask for 'all channels' without any input.

What is your use-case for this?  You don't need it for the console's channel-selector spinner.

**Comment by rjhowe** [comment]
It just would be nice to be able to know what channels are available and  currently have published content on them in case one wants test running a cluster using that channel.

**Comment by admiyo** [comment]
The ability to query for a specific form of data, priviledged or otherwise, is an access control decision, and should not be built into the structure of the application.  

The ability to query for all channels may well provide too much information for a user to be able to parse realistically.  Instead, there should be a way for a user to navigate to the set of information they require.

Imagine a future where there are 1000 channels.  A user might be subscribed to 10 of them.  If they wish to request access to more channels, the service needs a way to expose this information in a scalable manner.  Typically, this is done using a directed acyclic graph (DAG) of categories.  Essentially, this is the same kind of logic that Graph builder is already managing, just applied to the the channel abstraction as well as the individual images (IIUC).

 When a user makes a request like: 
https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.2
They are requesting a specific subgraph.  The query requested would make more sense to be something like:

https://api.openshift.com/api/upgrades_info/v1.1/channels

Which would list the set of available channels, with a link from each node to the query for that channel.  The set of channels available would be limited based on the users access control.  A channel would be in one of 3 states:  subscribed, available, or invisible.  Only the first two states would be returned.

Note that requiring a parameter like ?channel=a   breaks  discoverability; it makes it impossible to learn an API from direct queries.  


https://api.openshift.com/api/upgrades_info/v1.1/  should return:

{
channels: "https:..."
graph: "https:..."
}

**Comment by sferich888** [comment]
@admiyo this would work for my or supports needs to communicate available graphs (channels) to customers. +1 for this proposal.
