### ISSUE TITLE
[RFE] Expose latest versions available

### ISSUE THREAD

**Issue by e-minguez** [openshift/cincinnati#294]
Currently, to check the latest OCP version available this is needed:

```
curl -sH 'Accept: application/json' "https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.4&amd64" | jq -r '.nodes|map(.version)|.[]' | sort -V | tail -1
```

You need to know the minor version (4.4) and the channel (stable) beforehand.

It would be nice to expose that value in an API endpoint such as `https://api.openshift.com/api/latest` or `https://api.openshift.com/api/stable-4.4/latest` or `https://api.openshift.com/api/fast-4.4/latest`, etc.

I'm not sure if this RFE belongs here but just in case.

**Comment by sferich888** [comment]
This is only the latest version exposed  by the update graph, not necessarily the latest version of OCP that a customer can install. 
To get the latest version that Red Hat ships you would need to look at https://access.redhat.com/downloads/content/290/ (note the arch and version query parameters).

**Comment by wking** [comment]
What is your use-case?  Note that for install you can also use https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/ , https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.4/ , etc.

**Comment by e-minguez** [comment]
> This is only the latest version exposed by the update graph, not necessarily the latest version of OCP that a customer can install.

Shouldn't those two be the same for "stable-4.X" or "fast-4.X"?

> To get the latest version that Red Hat ships you would need to look at https://access.redhat.com/downloads/content/290/ (note the arch and version query parameters).

> What is your use-case? Note that for install you can also use https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/ , https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.4/ , etc.

My use case is none :smile: but I think that as a user it would be nice to know which is the latest available version easily... and even better, to have a dashboard/site/something with the latest versions (basically to avoid me doing this https://github.com/e-minguez/openshift-versions http://versions.openshift.tips/ )

**Comment by wking** [comment]
>  ....but I think that as a user it would be nice to know which is the latest available version easily...

"What is the latest version I can update $THIS_CLUSTER to?" is actionable, and already available via ClusterVersion's `status.availableUpdates`.  After users view your generic (not cluster-specific) latest-version page, what action are they empowered to take?

**Comment by e-minguez** [comment]
> > ....but I think that as a user it would be nice to know which is the latest available version easily...
> 
> "What is the latest version I can update $THIS_CLUSTER to?" is actionable, and already available via ClusterVersion's `status.availableUpdates`. After users view your generic (not cluster-specific) latest-version page, what action are they empowered to take?

AFAIK in a disconnected environment you won't be able to know if there is an available update unless you explicitly do the mirroring stuff (or visit https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/ or https://access.redhat.com/downloads/content/290/)

In any case, I just wanted to have something to take a look to see the latest OCP versions available, so feel free to close this.

**Comment by wking** [comment]
> AFAIK in a disconnected environment you won't be able to know if there is an available update unless you explicitly do the mirroring stuff...

There is some internal discussion around how to handle this, but at the moment the options are:

a. Ship the full, external graph (possibly for all channels/arches) in to the restricted-network environment, so a local tool that knows about local cluster versions/arches/channels can suggest what to mirror next.
b. User ships their current version/arch/channel out from the restricted-network environment, so an external tool can suggest what to mirror next.

Those are not mutually exclusive.  But they are both more cluster-specific than a generic "latest version" API, so I'll close this issue.

/close
