### ISSUE TITLE
Request Add CORS support

### ISSUE THREAD

**Issue by kunyan** [openshift/cincinnati#365]
Hi, 

Our team want to use the api `/api/upgrades_info/v1/graph`  in a frontend app.
but the API not support called by JavaScript from other domain.
Is that possible to support it ?

I think it should be easy to support by add a middleware https://docs.rs/actix-cors/0.5.4/actix_cors/

Then, the frontend developer could use the api with following code

```
fetch("https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.5")
    .then(res => res.json())
    .then((result)=> console.log(result))
```

**Comment by LalatenduMohanty** [comment]
We are tracking this in https://issues.redhat.com/browse/OTA-113 and there is a PR https://github.com/openshift/cincinnati/pull/196 for this

**Comment by kunyan** [comment]
Issue fixed

Test on Chrome console
```
fetch("https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.6")
  .then((res) => res.json())
  .then((result) => console.log(result));
```
