### ISSUE TITLE
design/cincinnati: clarify some details on the graph endpoint

### ISSUE THREAD

**Issue by lucab** [openshift/cincinnati#6]
A spec clarification request to @crawford on https://github.com/openshift/cincinnati/blob/95db15a823b231636c7a3aaeef25b6c22e6c9a8b/docs/design/cincinnati.md#graph-api.

The current implementation in `cincinnati` is stricter than the design spec, and these are the points that I'd like to have explicitly noted regarding the JSON API of the `graph` endpoint:
 * is `version` a freeform string or a semver label?
 * is a `""` allowed as a `version` value?
 * must a `version` value be unique in the "nodes" array?
 * is the `payload` field required and is an empty-string allowed there?
 * is the client supposed to pass additional parameters somehow (e.g. as query parameters)?
 * is the edges "empty object for future use" still a thing? (it isn't in example nor in deserializer code)

**Comment by crawford** [comment]
>  * is `version` a freeform string or a semver label?

Right now, it is semver. We might want to consider switching to the RPM versioning at some point.

>  * is a "" allowed as a version value?

No.

>  * must a version value be unique in the "nodes" array?

Yes. The version value is the identifier for a release. That cannot be ambiguous.

>  * is the payload field required and is an empty-string allowed there?

It is required. Right now we allow it to be an empty string, but we might want to disallow that.

>  * is the client supposed to pass additional parameters somehow (e.g. as query parameters)?

Yes, the client can pass query parameters in its request upstream. The contract for those parameters is defined by the client and Policy Engine implementation.

>  * is the edges "empty object for future use" still a thing? (it isn't in example nor in deserializer code)

Ah, I fixed that a while ago. I forgot to remove it from the documentation.

**Comment by lucab** [comment]
Thanks, I'll update the docs with those details then.

Two followups:
 * `version`: it sounds like we may want to define that as a plain "required unique non-empty JSON string" and leave semantic validation (semver, NEVRA or whatever) to higher-level consumers, ack?
 * `payload`: I don't foresee a usecase for an empty string but I think it doesn't hurt allowing that (as it isn't a main key/id anyway)

**Comment by crawford** [comment]
Both of those sound good.

**Comment by steveej** [comment]
> `version`: it sounds like we may want to define that as a plain "required unique non-empty JSON string" and leave semantic validation (semver, NEVRA or whatever) to higher-level consumers, ack?

It seems like we're looking fro a `version_scheme` field or something similar which lets the higher-level consumer specify how they want to deal with versions.

**Comment by crawford** [comment]
That is overkill in this case. The Graph Builder and client are already coupled with respect to the payload. It would make sense to extend that coupling to include the payload's version.

**Comment by lucab** [comment]
For context: I'm here because fedora-coreos may likely end up using the cincinnati protocol for new-release dissemination. In that case, while I can't tell for sure what the future format of release version labels will be, I can imagine some non-semver options (like commit digest, NEVRA or such).

I guess that my need here is basically just a unique non-void identifier.

The other tricky concern I had here is that semver (or similar) carries implicit semantics that may contradict the DAG data. I.e. given two labels `1.0.11` and `1.0.12`, semver offers both absolute ordering and update-compatibility between those but the DAG is free to have an edge in the reverse direction or no edge at all.

**Comment by steveej** [comment]
@lucab 
> The other tricky concern I had here is that semver (or similar) carries implicit semantics that may contradict the DAG data. I.e. given two labels `1.0.11` and `1.0.12`, semver offers both absolute ordering and update-compatibility between those but the DAG is free to have an edge in the reverse direction or no edge at all.

To me this sounds like it would strengthen semver's (or any other version scheme's) stance. 


@crawford 
> That is overkill in this case. The Graph Builder and client are already coupled with respect to the payload. It would make sense to extend that coupling to include the payload's version.

Could you elaborate on the coupling a bit? The way I understand your explanation is that we have a coupling which is simply implicit to the code.
